### ISSUE TITLE
rvizのconfigの調整

### ISSUE THREAD

**Issue by at-wat** [KMiyawaki/rsj_pointcloud_test#4]
3D-URGとxtionで点の初期状態のチェックボックスが異なっているようです
(3D-URGはvoxelが選択)

**Comment by KMiyawaki** [comment]
Xtionの方も rviz -d view_filters.rviz でデフォルトの状態では
 /voxel のPointCloud2 だけにチェックが入っているように思います。修正していただいたのでしょうか。

**Comment by at-wat** [comment]
すみません逆でした。
3D-URGは上二つが選択、Xtionは下一つ(/voxel)が選択状態になっていると思います。
